   name:_Hello World Workflow

   on:
     push:
      branches:
         - master
     pull_request:
       branches:
         - main
     workflow_dispatch:

   jobs:
     hello:
       runs-on: ubentu-latest
       steps:
         - uses: actions/checkout@v2
         - name: hello world
           run: echo "Hello World"
           shell: bash
        
     goodbye:
       runs-on: ubentu-latest
       steps:
         - name: goodbye world
           run: echo "Goodbye world"
           shell: bash  
